apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "starship-tracker.fullname" . }}-config
  labels:
    app: {{ include "starship-tracker.name" . }}
data:
  galaxy_name: {{ .Values.env.GALAXY_NAME | quote }}
  starship_api_endpoint: {{ .Values.env.STARSHIP_API_ENDPOINT | quote }}
